import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "ARX Development",
  description: "Generated by ARX Development",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html dir={locale === "ar" ? "rtl" : "ltr"} lang={locale}>
      <NextIntlClientProvider locale={locale}>
        <body className="relative">
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
